@startuml BibliotecaCodigo
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

class Project {
  +id:  Integer
  +name:  String
  +description:  String
  +status:  String
  +standard_id:  Integer
  +file_name:  String
  +created_at:  Datetime
  +updated_at:  Datetime
}

class Standard {
  +id:  Integer
  +name:  String
  +description:  String
  +file_name:  String
  +created_at:  Datetime
  +updated_at:  Datetime
}

class Rule {
  +id:  Integer
  +standard_id:  Integer
  +name:  String
  +description:  String
  +created_at:  Datetime
  +updated_at:  Datetime
}

class Validation {
  +id:  Integer
  +project_id:  Integer
  +rule_id:  Integer
  +status:  Boolean
  +notes:  String
  +created_at:  Datetime
  +updated_at:  Datetime
}

class Account {
  +id:  Integer
  +name:  String
  +cnpj:  String
  +email:  String
  +active:  Boolean 
  +subscription:  String
  +created_at:  Datetime
  +updated_at:  Datetime
}

class UserAccount {
  +id:  Integer
  +user_id:  Integer
  +account_id:  Integer
  +active:  Boolean
  +role:  String
  +responsibility_value:  Integer
  +created_at:  Datetime
  +updated_at:  Datetime
}

@enduml